
-- ============================================================
-- SQL BUSINESS & SALES DATA ANALYSIS
-- ============================================================
-- Database : sales_analysis
-- Table    : sales
-- Purpose  : Analyze sales performance and identify
--            business insights using PostgreSQL.
-- ============================================

-- Analysis Areas:

-- ============================================================
-- 1. DATA EXPLORATION
-- ============================================================

-- Q1. View the complete sales dataset
SELECT *
FROM sales;


-- Q2. View key customer and sales information
SELECT customer_name,
       city,
       product,
       total_sales
FROM sales;


-- Q3. How many unique cities are represented in the sales data?
SELECT COUNT(DISTINCT city) AS unique_cities
FROM sales;

-- ============================================================
-- 2. PRODUCT ANALYSIS
-- ============================================================

-- Q4. What are the total sales generated by each product?
SELECT product,
       SUM(total_sales) AS product_sales
FROM sales
GROUP BY product
ORDER BY product_sales DESC;


-- Q5. Which products have the highest number of transactions?
SELECT product,
       COUNT(transaction_id) AS transaction_count
FROM sales
GROUP BY product
ORDER BY transaction_count DESC;


-- Q6. What is the average sales value per transaction for each product?
SELECT product,
       AVG(total_sales) AS average_sales
FROM sales
GROUP BY product
ORDER BY average_sales DESC;

-- ============================================================
-- 3. CATEGORY ANALYSIS
-- ============================================================

-- Q7. What are the completed sales generated by each product category?
SELECT category,
       SUM(total_sales) AS category_sales
FROM sales
WHERE status = 'Completed'
GROUP BY category
ORDER BY category_sales DESC;

-- ============================================================
-- 4. MONTHLY ANALYSIS
-- ============================================================

-- Q8. How do completed sales vary across different months?
SELECT TO_CHAR(date, 'Month') AS month,
       SUM(total_sales) AS monthly_sales
FROM sales
WHERE status = 'Completed'
GROUP BY TO_CHAR(date, 'Month'),
         EXTRACT(MONTH FROM date)
ORDER BY EXTRACT(MONTH FROM date);


-- Q9. How do completed sales vary across product categories each month?
SELECT TO_CHAR(date, 'Month') AS month,
       category,
       SUM(total_sales) AS monthly_sales
FROM sales
WHERE status = 'Completed'
GROUP BY month,
         category,
         EXTRACT(MONTH FROM date)
ORDER BY EXTRACT(MONTH FROM date);

-- ============================================================
-- 5. CITY ANALYSIS
-- ============================================================

-- Q10. Which cities generate the highest completed sales?
SELECT city,
       SUM(total_sales) AS city_sales
FROM sales
WHERE status = 'Completed'
GROUP BY city
ORDER BY city_sales DESC;

-- ============================================================
-- 6. PAYMENT METHOD ANALYSIS
-- ============================================================

-- Q11. Which payment methods generate the highest completed sales?
SELECT payment_method,
       SUM(total_sales) AS payment_sales
FROM sales
WHERE status = 'Completed'
GROUP BY payment_method
ORDER BY payment_sales DESC;


-- Q12. Which payment methods have the highest number of completed transactions?
SELECT payment_method,
       COUNT(transaction_id) AS transaction_count
FROM sales
WHERE status = 'Completed'
GROUP BY payment_method
ORDER BY transaction_count DESC;

-- ============================================================
-- 7. CUSTOMER ANALYSIS
-- ============================================================

-- Q13. Who are the top 5 customers by completed sales?
SELECT customer_name,
       SUM(total_sales) AS customer_sales
FROM sales
WHERE status = 'Completed'
GROUP BY customer_name
ORDER BY customer_sales DESC
LIMIT 5;

-- ============================================================
-- 8. TRANSACTION STATUS ANALYSIS
-- ============================================================

-- Q14. What is the number and sales value of transactions by status?
SELECT status,
       COUNT(transaction_id) AS status_transaction,
       SUM(total_sales) AS status_sales
FROM sales
GROUP BY status
ORDER BY status_sales DESC;

-- ============================================================