CREATE TABLE sales (
    transaction_id INT PRIMARY KEY,
    date DATE,
    customer_name VARCHAR(100),
    city VARCHAR(50),
    category VARCHAR(50),
    product VARCHAR(50),
    quantity INT,
    unit_price NUMERIC(10,2),
    total_sales NUMERIC(12,2),
    payment_method VARCHAR(30),
    status VARCHAR(30)
);

-- How many sales transactions are recorded in the dataset?

SELECT COUNT(*)
FROM sales;

-- What are the details of all sales transactions recorded in the dataset?

SELECT *
FROM sales;

-- What are the customers, their cities, and the sales amount associated with each transaction?

SELECT customer_name,city,total_sales
FROM sales;

-- What products were sold, in what quantities, and what was the sales amount for each transaction?

SELECT product,quantity,total_sales
FROM sales;

-- What sales transactions were recorded in Delhi?

SELECT * FROM sales
WHERE city = 'Delhi';

-- What sales transactions involved laptops?

SELECT *
FROM sales
WHERE product = 'Laptop';

-- What sales transactions were paid for using UPI?

SELECT * FROM sales
WHERE payment_method = 'UPI';

-- What are the total sales generated by each product?	

SELECT product,
SUM (total_sales) AS product_sales
FROM sales
GROUP BY product
ORDER BY product_sales DESC;

-- What are the top 5 highest-value transactions by sales amount?

SELECT transaction_id, product, city, total_sales
FROM sales
ORDER BY total_sales DESC
LIMIT 5;

-- What are the transactions ranked from highest to lowest by sales amount?

SELECT transaction_id, product, city, total_sales
FROM sales
ORDER BY total_sales DESC;

-- How many transactions did each product have?

SELECT product,
    COUNT(transaction_id) AS transaction_count
FROM sales
GROUP BY product
ORDER BY transaction_count DESC;

-- What is the average sales amount for each product?

SELECT product,
    AVG(total_sales) AS average_sales
FROM sales
GROUP BY product
ORDER BY average_sales DESC;

-- What was the highest-value individual transaction?

SELECT MAX(total_sales) AS highest_transaction
FROM sales;

-- What was the lowest-value individual transaction?

SELECT MIN(total_sales) AS lowest_transaction
FROM sales;

-- Which products generated more than ₹1,00,000 in total sales?

SELECT product,
       SUM(total_sales) AS product_sales
FROM sales
GROUP BY product
HAVING SUM(total_sales) > 100000
ORDER BY product_sales DESC;

-- How can we classify products according to their total sales performance?

SELECT product,
       SUM(total_sales) AS product_sales,
       CASE
           WHEN SUM(total_sales) >= 100000 THEN 'High'
           WHEN SUM(total_sales) >= 50000 THEN 'Medium'
           ELSE 'Low'
       END AS sales_category
FROM sales
GROUP BY product
ORDER BY product_sales DESC;

-- Among completed transactions in Delhi, which products generated more than ₹50,000
-- in total sales? Show the products from highest to lowest total sales.

SELECT product,
       SUM(total_sales) AS product_sales
FROM sales
WHERE city = 'Delhi'
  AND status = 'Completed'
GROUP BY product
HAVING SUM(total_sales) > 50000
ORDER BY product_sales DESC;

-- What are the total completed sales for each month?

SELECT TO_CHAR(date, 'Month') AS month,
       SUM(total_sales) AS monthly_sales
FROM sales
WHERE status = 'Completed'
GROUP BY month
ORDER BY monthly_sales DESC;

-- What are the total completed sales for each month, 
-- presented in chronological order from January to December?

SELECT TO_CHAR(date, 'Month') AS month,
       SUM(total_sales) AS monthly_sales
FROM sales
WHERE status = 'Completed'
GROUP BY TO_CHAR(date, 'Month'), EXTRACT(MONTH FROM date)
ORDER BY EXTRACT(MONTH FROM date);

-- How do completed sales vary across different product categories each month?

SELECT TO_CHAR(date, 'Month') AS month,
     category,
       SUM(total_sales) AS monthly_sales
FROM sales
WHERE status = 'Completed'
GROUP BY month, category, EXTRACT(MONTH FROM date)
ORDER BY EXTRACT(MONTH FROM date);

-- How many unique cities are represented in the sales dataset?

SELECT COUNT(DISTINCT city) AS unique_cities
FROM sales;

-- Which cities generated the highest completed sales, 
-- and what was the total sales amount from each city?

SELECT city, SUM(total_sales) AS city_sales
FROM sales
WHERE status = 'Completed'
GROUP BY city
ORDER BY city_sales DESC;

-- How much completed sales were generated through each payment method?

SELECT payment_method, SUM(total_sales) AS payment_sales
FROM sales
WHERE status = 'Completed'
GROUP BY payment_method
ORDER BY payment_sales DESC;

-- Which sales categories generate the highest total completed sales?

SELECT category,
       SUM(total_sales) AS category_sales
FROM sales
WHERE status = 'Completed'
GROUP BY category
ORDER BY category_sales DESC;

-- How many completed transactions were made using each payment method?

SELECT payment_method, 
       COUNT(transaction_id) AS transaction_count
FROM sales
WHERE status = 'Completed'
GROUP BY payment_method
ORDER BY transaction_count DESC;

-- What is the average sales amount for each product, ranked from highest to lowest?

SELECT product, AVG(total_sales) AS avg_sales
FROM sales
GROUP BY product
ORDER BY avg_sales DESC;

-- What is the highest single transaction value recorded for each product, ranked from highest to lowest?

SELECT product, MAX(total_sales) AS max_sales
FROM sales
GROUP BY product
ORDER BY max_sales DESC;

-- What is the lowest single transaction value recorded for each product, ranked from lowest to highest?

SELECT product,
       MIN(total_sales) AS min_sales
FROM sales
GROUP BY product
ORDER BY min_sales ASC;

-- What are the total completed sales generated by each product category, ranked from highest to lowest?

SELECT category,
       SUM(total_sales) AS category_sales
FROM sales
WHERE status = 'Completed'
GROUP BY category
ORDER BY category_sales DESC;

-- Which products generated more than ₹100,000 in completed sales,
-- and what were their total sales?

SELECT product,
       SUM(total_sales) AS product_sales
FROM sales
WHERE status = 'Completed'
GROUP BY product
HAVING SUM(total_sales) > 100000
ORDER BY product_sales DESC;

-- How much completed sales did each product generate in each city, ranked from highest to lowest?

SELECT city,
       product,
       SUM(total_sales) AS product_sales
FROM sales
WHERE status = 'Completed'
GROUP BY city, product
ORDER BY product_sales DESC;

-- Which 5 customers generated the highest completed sales?

SELECT customer_name,
       SUM(total_sales) AS customer_sales
FROM sales
WHERE status = 'Completed'
GROUP BY customer_name
ORDER BY customer_sales DESC
LIMIT 5;

-- How much completed sales did the business generate in each month, in chronological order?

SELECT TO_CHAR(date, 'Month') AS month,
       SUM(total_sales) AS monthly_sales
FROM sales
WHERE status = 'Completed'
GROUP BY TO_CHAR(date, 'Month'),
         EXTRACT(MONTH FROM date)
ORDER BY EXTRACT(MONTH FROM date) ASC;

-- How much completed sales did each product category generate
-- in each city, ranked from highest to lowest?

SELECT city,
       category,
       SUM(total_sales) AS category_sales
FROM sales
WHERE status = 'Completed'
GROUP BY city, category
ORDER BY category_sales DESC;

-- How many completed transactions and how much completed
-- sales were generated through each payment method?

SELECT payment_method,
       COUNT(transaction_id) AS total_transaction,
       SUM(total_sales) AS transaction_sales
FROM sales
WHERE status = 'Completed'
GROUP BY payment_method
ORDER BY transaction_sales DESC;

-- How many transactions are in each status, and what is
-- the total sales value associated with each status?

SELECT status,
       COUNT(transaction_id) AS status_transaction,
       SUM(total_sales) AS status_sales
FROM sales
GROUP BY status
ORDER BY status_sales DESC;

-- How can we classify each transaction based on its sales value as Low, Medium, or High?

SELECT transaction_id,
       product,
       total_sales,
       CASE
           WHEN total_sales >= 50000 THEN 'High'
           WHEN total_sales >= 20000 THEN 'Medium'
           ELSE 'Low'
       END AS sales_category
FROM sales;

-- Which products sold the highest number of units, ranked from highest to lowest?

SELECT product,
       SUM(quantity) AS total_quantity
FROM sales
GROUP BY product
ORDER BY total_quantity DESC;

-- What is the average sales amount per transaction in each city?

SELECT city,
       SUM(total_sales) / COUNT(transaction_id) AS avg_order_value
FROM sales
GROUP BY city
ORDER BY avg_order_value DESC;

-- Which 5 completed transactions generated the highest sales value?

SELECT transaction_id,
       customer_name,
       product,
       city,
       total_sales
FROM sales
WHERE status = 'Completed'
ORDER BY total_sales DESC
LIMIT 5;

-- Which products generated the most completed sales,
-- and how many transactions contributed to those sales?

SELECT product,
       SUM(total_sales) AS product_sales,
       COUNT(transaction_id) AS product_transaction
FROM sales
WHERE status = 'Completed'
GROUP BY product
ORDER BY product_sales DESC;